### PR TITLE
Java Code Refactoring

### PR DESCRIPTION
**Pull request by matthewhillier**
Working through the Java Gatherer to refactor the code, reduce complexity, improve robustness and set us up for improving the solution and the stats in the future.

### CODE REVIEW

**Comment by matthewhillier** [comment]
Hey @Pricetx, @ReidWeb,

Quick question for you both on how you're running the gatherer: How many of these different command-line options are you actively using?

I've got a few here I'd like to actively cull to make the code more predictable, e.g.:

- Remove anything that impacts the table structure
  - This is making it very difficult to improve table management and have a robust way to have "upgrade-scripts"
  - Don't necessarily have to change the behaviour (NULL value in the table is better than not knowing whether a column will exist or not)
- Remove the logging "volume" switches
  - Looking to move the `System.out` calls to use a logger, such as log4j, so that we can better control where the logging goes (console, log file, separated logs, etc)
  - Note, this butchers a chunk of the unit tests, which are relying on the System.out stream, so these need to be reviewed and rationalised
- Remove 'split-table' mode
  - This is just pure simplification :)

I'm aiming to rationalise the basics here, so that I can start looking at things which would help us scale this in the future, such as keeping a persistent database, keeping some history to enable us to report on trends, enabling automated gathering, etc. Lots of ideas 😄 

Cheers!

**Comment by ReidWeb** [comment]
Do it all IMO 👍 

Yeah the unit tests suck, sorry see XIVStats/XIVStats#12

**Comment by matthewhillier** [comment]
Options streamlined and log4j added 😄 Updated the HttpStatus handling to use the libraries native exception types.

To Do:
- Separate file-based log to write character parse status

I'll probably stop this branch here and give us a chance to review and tidy. Next steps after this get a bit more invasive 😉

**Comment by matthewhillier** [comment]
Progress logging is now enabled for the Gatherer. 2 new log files will be generated when running the JAR under the ```./ffxivcensus/``` directory; the ```progress.log``` file being the one to track basic character parsing progress.

**Comment by matthewhillier** [comment]
Hey @ReidWeb - I'm getting failures from Jenkins that aren't showing up in ci.reidweb.com (latest was build 4 for this branch, which seems to be MIA and references an issue using JDK8).

Is there a rogue worker out there somewhere, or is the public jenkins not showing everything?

Cheers!

**Comment by ReidWeb** [comment]
@matthewhillier there may have been a degredation in mail, not too sure.

Also possible you're seeing the 'pull request' builds fail, and you aren't seeing them, it's a bit strange it runs PR builds and branch builds.

**Comment by matthewhillier** [comment]
Can't see any Pull Request builds, but they could be private. The link I'm getting (and is showing on this Pull Requests under the Jenkins failure) is [https://ci.reidweb.com/job/XIVStats/job/XIVStats-Gatherer-Java/job/refactoring/5/display/redirect](https://ci.reidweb.com/job/XIVStats/job/XIVStats-Gatherer-Java/job/refactoring/5/display/redirect), but that doesn't go anywhere.

Either way, the latest run available on Jenkins shows failures writing to the database. I'm assuming there's a persistent DB underneath which probably needs removing as it's out of sync with the Stormblood update.

**Comment by ReidWeb** [comment]
May be a permission issue, shouldn't matter too much they're just repeated builds of the branch builds. Will investigate access/turning them off on Monday.

I believe the db is now hosted on @Pricetx's infrastructure, worth investigating.

**Comment by ReidWeb** [comment]
Ooh Spring, nice. Great work, will look to resolve CI issues this weekend

**Comment by matthewhillier** [comment]
The DB now self-maintains using liquibase, however in order to sync everything up, I've instructed it to drop the `tblplayers` table as it's first action, and then re-create the structure at the 1.4.0 / Stormblood configuration.

This shouldn't be an issue as it doesn't appear like we're expecting our DB to be persistent at the moment, but please take note :)

**Comment by matthewhillier** [comment]
I'm done here. Have some interesting ideas on how to evolve this for a 2.0 version, but I'll save that for another discussion / branch. For now, this is open for review and merging when ready. 😄

**Review by ReidWeb — APPROVED** [review]
LGTM 👍 

If you're ready for merge I can merge.

Are there any DB changes @Pricetx and @XIVStats/consumers will need to be notified of?

**Comment by ReidWeb** [comment]
Hmm... getting an error in CI

https://ci.reidweb.com/job/XIVStats/job/XIVStats-Gatherer-Java/job/refactoring/9/console

Is this an app error or do I need to dig into the CI setup?

**Comment by Pricetx** [comment]
Peter and I looked at the CI. It uses a database hosted on my server. The original error was due to the table it was reading missing the new column. However, after manually dropping the table it looks like the CI is now failing because the table isn't being automatically recreated.

I believe the Java application should be trying to create the table if it doesn't exist whenever it starts running, but that doesn't appear to be working in this situation.

**Review by ReidWeb — CHANGES_REQUESTED** [review]
Please review @Pricetx's comment ref table initialization.

**Comment by matthewhillier** [comment]
Hmmm... 😕 (this is my confused face).

So I can see the point in the logs where liquibase checked the schema to see whether it needed to run or not:

```
Running com.ffxivcensus.gatherer.GathererControllerIT
INFO 27/11/17 19:20: liquibase: Successfully acquired change log lock
INFO 27/11/17 19:21: liquibase: Reading from ffxivcensus_dev.DATABASECHANGELOG
INFO 27/11/17 19:21: liquibase: Successfully released change log lock
```

However, this would typically tell me that it found nothing to do.

When liquibase runs, it creates two additional tables in the schema (`ffxivcensus_dev`), `DATABASECHANGELOG` and `DATABASECHANGELOGLOCK`. These act as a version-control mechanism which tells liquibase which adjustments have already been made to the DB and at what "version" it's at.

If there's _any_ changes to the tables that are done outside of liquibase, then it can't account for them and so the result of running it is basically unknown.

I've tried multiple combinations locally, and I can only assume that the the two `DATABASECHANGELOG` and `DATABASECHANGELOGLOCK` have been left in-tact while the `tblplayers` was either modified or rolled-back somehow.

It shouldn't be a major issue at this point, but if that's the case then I'd suggest just nuke the `ffxivcensus_dev` schema, re-create it and leave it blank, and then re-run the CI build. Liquibase should then kick in to re-init the necessary tables. In all other environments, that will happen anyway as the scripts for the DB all start with, essentially, `DROP TABLE IF EXISTS tblplayers`.

If you're not comfortable doing that, then DROP `DATABASECHANGELOG` and `DATABASECHANGELOGLOCK` and liquibase should start again from Rev 0.

**Comment by Pricetx** [comment]
Ahh.

Yes, I can confirm those two tables still exited but tblplayers did not. I have now removed them and will kick off another CI run.

**Comment by ReidWeb** [comment]
CI build passing, will do a final review of code later.

@Pricetx will be doing a review of impacts to database schema.

**Review by ReidWeb — APPROVED** [review]

**Pull request merged**
