### PR TITLE
#61 - Endwalker 6.0 Updates

### PR DESCRIPTION
**Pull request by matthewhillier**
Updated the Gatherer to reflect the changes to the Lodestone with patch 6.0 Endwalker. Includes:

* Added Reaper and Sage jobs
* Added Resistance Rank (preliminary)

Changes to the database feed the update to the PHP scripts under the branch: https://github.com/XIVStats/XIVStats/tree/52-endwalker-6.0

### CODE REVIEW

**Comment by Pricetx** [comment]
I have run a test of the Gatherer on IDs 19,000,000 to 19,100,000. The Gatherer seems to have successfully gathered data as expected.

I then ran the latest PHP against it, the results of which can be seen here: https://s3.eu-west-2.amazonaws.com/dev.ffxivcensus.com/index.html 

I received the following warnings from the PHP when executing:
PHP Notice:  Undefined variable: shb_collectors in /opt/ffxivcensus/dev/template.php on line 227                                                                
PHP Notice:  Undefined variable: sbartbooktwo in /opt/ffxivcensus/dev/template.php on line 243                                                                  
PHP Notice:  Undefined index: female in /opt/ffxivcensus/dev/template.php on line 47                                                                            
PHP Notice:  Undefined index: female in /opt/ffxivcensus/dev/template.php on line 47                                                                            
PHP Notice:  Undefined index: female in /opt/ffxivcensus/dev/template.php on line 47 

I haven't had an opportunity to determine whether these errors are due to data missing from the Gatherer (including the possibility that the 100,000 IDs scanned didn't find any results for certain mounts / minions), or whether it is an issue specifically with the PHP. If the latter, this should probably be raised as an issue on that project instead.

Once we've confirmed the source of those errors, I'm happy to merge this in.

Thanks!

**Review by ReidWeb — APPROVED** [review]

**Comment by ReidWeb** [comment]
Code looks good,

- [ ]  please await Jonathan's approval before merge though

**Comment by matthewhillier** [comment]
Thanks @Pricetx! Can you check the latest version of `master` on the php project? The test sample appears to be from an older build, and not the changes submitted under https://github.com/XIVStats/XIVStats/pull/53, in which I _think_ all of those PHP warnings are resolved 🙏 

For reference, the new build of XIVStats should produce something like the attached: [index.zip](https://github.com/XIVStats/XIVStats-Gatherer-Java/files/7682683/index.zip)

**Comment by Pricetx** [comment]
Hi,

Apologies for the delay there. You're quite correct, the script I was using to automate it was not referring to the path I thought it was, leading me to run an older version of the PHP.

The latest version is completing without error, and can also be previewed here: https://s3.eu-west-2.amazonaws.com/dev.ffxivcensus.com/index.html

I'm going to approve the merge and kick off a census hopefully tonight.

Thanks once again!

**Pull request merged**
